server:
  port: 8001


nettyServer:
  name: rpc-Server
  port: 30001
  discoveryIp: 127.0.0.1
  nacos:
    addr: 127.0.0.1:8848
    username: nacos
    password: nacosdev

logging:
  level:
    com:
      tyc:
        provider: DEBUG


