server:
  port: 8002

client:
  host: 127.0.0.1
  port: 30001
  threadNum: 8
  serviceName: rpc-Server
  scanPath: com.tyc.consumer
  nacos:
    addr: 127.0.0.1:8848
    username: nacos
    password: nacosdev
logging:
  level:
    com:
      tyc:
        consumer: DEBUG
